version: '3.8'

services:

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    runtime: nvidia
    ports:
      - "11434:11434"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ollama.rule=Host(`ollama.zimos3d.com`)"
      - "traefik.http.routers.ollama.entrypoints=websecure"
      - "traefik.http.routers.ollama.tls=true"
      - "traefik.http.routers.ollama.tls.certresolver=myresolver"

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434
      - OPENAI_API_KEY=none
    volumes:
      - openwebui_data:/app/backend/data
    networks:
      - web
    depends_on:
      - ollama
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openwebui.rule=Host(`zgpt.zimos3d.com`)"
      - "traefik.http.routers.openwebui.entrypoints=websecure"
      - "traefik.http.routers.openwebui.tls=true"
      - "traefik.http.routers.openwebui.tls.certresolver=myresolver"


  foundryvtt:
    image: felddy/foundryvtt:12.343.0
    restart: unless-stopped
    environment:
      - FOUNDRY_USERNAME=${FOUNDRY_USERNAME}
      - FOUNDRY_PASSWORD=${FOUNDRY_PASSWORD}
      - FOUNDRY_ADMIN_KEY=${FOUNDRY_ADMIN_KEY}
      - FOUNDRY_PROXY_SSL=true
      - FOUNDRY_PROXY_PORT=443
      - FOUNDRY_HOSTNAME=${FOUNDRY_HOSTNAME}
    volumes:
      - foundry_data:/data
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.foundry.rule=Host(`foundry.zimos3d.com`)"
      - "traefik.http.routers.foundry.entrypoints=websecure"
      - "traefik.http.routers.foundry.tls=true"
      - "traefik.http.routers.foundry.tls.certresolver=myresolver"


  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: n8n
      POSTGRES_USER: n8n_user
      POSTGRES_PASSWORD: ${N8N_DB_PASSWORD}
    volumes:
      - n8n_postgres_data:/var/lib/postgresql/data
    networks:
      - web

  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n_user
      - DB_POSTGRESDB_PASSWORD=${N8N_DB_PASSWORD}
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
      - WEBHOOK_TUNNEL_URL=https://n8n.zimos3d.com
      - WEBHOOK_URL=https://n8n.zimos3d.com
      - N8N_WEBHOOK_URL=https://n8n.zimos3d.com
      - N8N_HOST=n8n.zimos3d.com
      - N8N_PROTOCOL=https
      - N8N_PORT=5678

    volumes:
      - n8n_data:/home/node/.n8n
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`n8n.zimos3d.com`)"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.tls.certresolver=myresolver"

    depends_on:
      - postgres
    networks:
      - web

  comfyui:
    image: obeliks/comfyui:master-cu118
    restart: unless-stopped
    runtime: nvidia  
    networks:
      - web
    ports:
      - "8188:8188"  
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all  
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.comfyui.rule=Host(`comfy.zimos3d.com`)"
      - "traefik.http.routers.comfyui.entrypoints=websecure"
      - "traefik.http.routers.comfyui.tls=true"
    volumes:
      - comfyui_data:/workspace
      - /mnt/e/selfhosted/comfyui_data/models:/app/models  # Persistent model storage
      - /mnt/e/selfhosted/comfyui_data/input:/app/input    # Optional: input images
      - /mnt/e/selfhosted/comfyui_data/output:/app/output  # Optional: output images

  # invokeai:
  #   image: ghcr.io/invoke-ai/invokeai:latest
  #   restart: unless-stopped
  #   ports:
  #     - "9090:9090"  # WebUI
  #   volumes:
  #     - invoke_data:/invokeai
  #   environment:
  #     - INVOKEAI_WEB=1
  #     - NVIDIA_VISIBLE_DEVICES=all
  #     - NVIDIA_DRIVER_CAPABILITIES=all 
  #   networks:
  #     - web
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.invokeai.rule=Host(`invokeai.zimos3d.com`)"
  #     # - "traefik.http.services.invokeai.loadbalancer.server.port=9090"
  #     - "traefik.http.routers.invokeai.entrypoints=websecure"
  #     - "traefik.http.routers.invokeai.tls.certresolver=letsencrypt"

  whisper:
    container_name: whisper-asr
    image: onerahmet/openai-whisper-asr-webservice:latest-gpu
    restart: unless-stopped
    ports:
      - "9001:9000"
    environment:
      - ASR_ENGINE=whisperx
      - ASR_MODEL=medium
      - HF_TOKEN=${HUGGINGFACE_TOKEN}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - WHISPER_URL=http://whisper:9001 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - whisper_models:/root/.cache/whisper
    networks:
      - web

    
networks:
  web:
    external: true



volumes:

  ollama_data:
    driver: local
  openwebui_data:
    driver: local
  foundry_data:
    driver: local
  n8n_data:
    driver: local
  n8n_postgres_data:
    driver: local
  comfyui_data:
    driver: local
  whisper_models:
    driver: local
  # invoke_data:
  #   driver: local
